//
//  Notifications.swift
//  BluetoothTest
//
//  Created by Daniel on 2025/2/13.
//

enum DataNotifications : String {
    
    
    case DATA_RECEIVED = "DATA_RECEIVED"
    case CHANNEL_CLOSED = "CHANNEL_CLOSED"
    case CONNECTED = "CONNECTED_TO_NOTHING"
    case FOUND = "FOUND"
    case FAILED_TO_CONNECT = "FAILED_TO_CONNECT"
    case OPENNED_RFCOMM_CHANNEL = "OPENNED_RFCOMM_CHANNEL"
    case FAILED_TO_OPEN_RFCOMM_CHANNEL = "FAILED_TO_OPEN_RFCOMM_CHANNEL"
    case DATA_UPDATED = "DATA_UPDATED"
    case REPOSITORY_DATA_UPDATED = "REPOSITORY_DATA_UPDATED"
    case EAR_TIP_TEST_RESULT = "EAR_TIP_TEST_RESULT"
    
    
}
